status is-interactive; and begin
    # Abbreviations
    abbr --add --position anywhere --set-cursor -- /b /boot/%
    abbr --add --position anywhere --set-cursor -- /bi /bin/%
    abbr --add --position anywhere --set-cursor -- /c /containers/%
    abbr --add --position anywhere --set-cursor -- /d /dev/%
    abbr --add --position anywhere --set-cursor -- /dd /dev/disk/%
    abbr --add --position anywhere --set-cursor -- /ddb /dev/disk/by-%
    abbr --add --position anywhere --set-cursor -- /e /etc/%
    abbr --add --position anywhere --set-cursor -- /en /etc/nixos/%
    abbr --add --position anywhere --set-cursor -- /h '~/%'
    abbr --add --position anywhere --set-cursor -- /h.c '~/.config/%'
    abbr --add --position anywhere --set-cursor -- /h.d '~/.dev/%'
    abbr --add --position anywhere --set-cursor -- /h.l '~/.local/%'
    abbr --add --position anywhere --set-cursor -- /h.lb '~/.local/bin/%'
    abbr --add --position anywhere --set-cursor -- /h.ls '~/.local/share/%'
    abbr --add --position anywhere --set-cursor -- /h.s '~/.ssh/%'
    abbr --add --position anywhere --set-cursor -- /hde '~/Desktop/%'
    abbr --add --position anywhere --set-cursor -- /hdo '~/Downloads/%'
    abbr --add --position anywhere --set-cursor -- /hdoc '~/Documents/%'
    abbr --add --position anywhere --set-cursor -- /hm '~/Music/%'
    abbr --add --position anywhere --set-cursor -- /hp '~/Pictures/%'
    abbr --add --position anywhere --set-cursor -- /hps '~/Pictures/Screenshots/%'
    abbr --add --position anywhere --set-cursor -- /hpub '~/Public/%'
    abbr --add --position anywhere --set-cursor -- /hs '~//home/myned/SYNC/%'
    abbr --add --position anywhere --set-cursor -- /hv '~/Videos/%'
    abbr --add --position anywhere --set-cursor -- /m /mnt/%
    abbr --add --position anywhere --set-cursor -- /ml /mnt/local/%
    abbr --add --position anywhere --set-cursor -- /mr /mnt/remote/%
    abbr --add --position anywhere --set-cursor -- /n /nix/%
    abbr --add --position anywhere --set-cursor -- /nv /nix/var/%
    abbr --add --position anywhere --set-cursor -- /nvn /nix/var/nix/%
    abbr --add --position anywhere --set-cursor -- /nvnp /nix/var/nix/profiles/%
    abbr --add --position anywhere --set-cursor -- /nvnps /nix/var/nix/profiles/system/%
    abbr --add --position anywhere --set-cursor -- /o /opt/%
    abbr --add --position anywhere --set-cursor -- /p /proc/%
    abbr --add --position anywhere --set-cursor -- /r /run/%
    abbr --add --position anywhere --set-cursor -- /rc /run/current-system/%
    abbr --add --position anywhere --set-cursor -- /ro /root/%
    abbr --add --position anywhere --set-cursor -- /s /srv/%
    abbr --add --position anywhere --set-cursor -- /sy /sys/%
    abbr --add --position anywhere --set-cursor -- /syc /sys/class/%
    abbr --add --position anywhere --set-cursor -- /t /tmp/%
    abbr --add --position anywhere --set-cursor -- /u /usr/%
    abbr --add --position anywhere --set-cursor -- /ub /usr/bin/%
    abbr --add --position anywhere --set-cursor -- /v /var/%
    abbr --add --position anywhere --set-cursor -- /vl /var/lib/%
    abbr --add --position anywhere --set-cursor -- /vlo /var/log/%
    abbr --add --position anywhere --set-cursor -- /vr /var/run/%
    abbr --add --set-cursor -- a adb
    abbr --add --set-cursor -- as 'adb shell'
    abbr --add --set-cursor -- asa 'adb shell sh /sdcard/Android/data/com.llamalab.automate/cache/start.sh'
    abbr --add --set-cursor -- b 'sudo borgmatic --progress --stats'
    abbr --add --set-cursor -- bb 'sudo borgmatic borg'
    abbr --add --set-cursor -- bc 'sudo borgmatic create --progress --stats'
    abbr --add --set-cursor -- bct 'sudo borgmatic compact'
    abbr --add --set-cursor -- be 'sudo borgmatic extract --progress'
    abbr --add --set-cursor -- bi 'sudo borgmatic info'
    abbr --add --set-cursor -- bin 'sudo borgmatic init -e repokey-blake2'
    abbr --add --set-cursor -- bk 'sudo borgmatic key export'
    abbr --add --set-cursor -- bl 'sudo borgmatic list'
    abbr --add --set-cursor -- bm 'sudo borgmatic mount'
    abbr --add --set-cursor -- bp 'sudo borgmatic prune'
    abbr --add --set-cursor -- br 'sudo borgmatic restore'
    abbr --add --set-cursor -- brl 'sudo borgmatic rlist'
    abbr --add --set-cursor -- bt 'sudo borgmatic export-tar'
    abbr --add --set-cursor -- bu 'sudo borgmatic unmount'
    abbr --add --set-cursor -- c clear
    abbr --add --set-cursor -- cz chezmoi
    abbr --add --set-cursor -- cza 'chezmoi add'
    abbr --add --set-cursor -- czaf 'chezmoi add --follow'
    abbr --add --set-cursor -- czc 'chezmoi cat'
    abbr --add --set-cursor -- czcd 'chezmoi cd'
    abbr --add --set-cursor -- czd 'chezmoi diff'
    abbr --add --set-cursor -- czdoc 'chezmoi doctor'
    abbr --add --set-cursor -- cze 'chezmoi edit'
    abbr --add --set-cursor -- czew 'chezmoi edit --watch'
    abbr --add --set-cursor -- czey 'chezmoi edit --apply'
    abbr --add --set-cursor -- czg 'chezmoi git'
    abbr --add --set-cursor -- czi 'chezmoi init'
    abbr --add --set-cursor -- czia 'chezmoi init --apply'
    abbr --add --set-cursor -- cziam 'chezmoi init --apply myned'
    abbr --add --set-cursor -- czm 'chezmoi merge'
    abbr --add --set-cursor -- czma 'chezmoi merge-all'
    abbr --add --set-cursor -- czr 'chezmoi re-add'
    abbr --add --set-cursor -- czs 'chezmoi status'
    abbr --add --set-cursor -- czt 'chezmoi chattr --recursive'
    abbr --add --set-cursor -- cztn 'chezmoi chattr --recursive noexecutable,noreadonly'
    abbr --add --set-cursor -- czu 'chezmoi update'
    abbr --add --set-cursor -- czx 'chezmoi execute-template'
    abbr --add --set-cursor -- czy 'chezmoi apply'
    abbr --add --set-cursor -- d 'docker'
    abbr --add --set-cursor -- dc 'docker compose'
    abbr --add --set-cursor -- dcd 'docker compose down'
    abbr --add --set-cursor -- dce 'docker compose exec'
    abbr --add --set-cursor -- dcl 'docker compose logs'
    abbr --add --set-cursor -- dcp 'docker compose pull'
    abbr --add --set-cursor -- dcu 'docker compose up'
    abbr --add --set-cursor -- dcuf 'docker compose up --force-recreate'
    abbr --add --set-cursor -- dd 'sudo dd if=% of= status=progress'
    abbr --add --set-cursor -- de 'docker exec'
    abbr --add --set-cursor -- dei 'docker exec --interactive'
    abbr --add --set-cursor -- deit 'docker exec --interactive --tty'
    abbr --add --set-cursor -- det 'docker exec --tty'
    abbr --add --set-cursor -- di 'docker images'
    abbr --add --set-cursor -- dir direnv
    abbr --add --set-cursor -- dira 'direnv allow'
    abbr --add --set-cursor -- dire 'direnv edit'
    abbr --add --set-cursor -- dirr 'direnv reload'
    abbr --add --set-cursor -- dirs 'direnv status'
    abbr --add --set-cursor -- dirt 'direnv export'
    abbr --add --set-cursor -- dirx 'direnv exec'
    abbr --add --set-cursor -- dk 'docker kill'
    abbr --add --set-cursor -- dn 'docker network'
    abbr --add --set-cursor -- dnl 'docker network ls'
    abbr --add --set-cursor -- dp 'docker pull'
    abbr --add --set-cursor -- dps 'docker ps'
    abbr --add --set-cursor -- dpsa 'docker ps --all --size'
    abbr --add --set-cursor -- dpsf 'docker ps --format='\''table {{.ID}}\t{{.Names}}\t{{.Status}}'\'''
    abbr --add --set-cursor -- dr 'docker rm'
    abbr --add --set-cursor -- ds 'docker system'
    abbr --add --set-cursor -- dsp 'docker system prune'
    abbr --add --set-cursor -- dspav 'docker system prune --all --volumes'
    abbr --add --set-cursor -- e exit
    abbr --add --set-cursor -- g git
    abbr --add --set-cursor -- ga 'git add'
    abbr --add --set-cursor -- gb 'git branch'
    abbr --add --set-cursor -- gbi 'git bisect'
    abbr --add --set-cursor -- gbib 'git bisect bad'
    abbr --add --set-cursor -- gbig 'git bisect good'
    abbr --add --set-cursor -- gc 'git clone'
    abbr --add --set-cursor -- gco 'git commit'
    abbr --add --set-cursor -- gd 'git diff'
    abbr --add --set-cursor -- gf 'git fetch'
    abbr --add --set-cursor -- gi 'git init'
    abbr --add --set-cursor -- gk 'git checkout'
    abbr --add --set-cursor -- gl 'git log'
    abbr --add --set-cursor -- gm 'git merge'
    abbr --add --set-cursor -- gp 'git pull'
    abbr --add --set-cursor -- gps 'git push'
    abbr --add --set-cursor -- gr 'git reset'
    abbr --add --set-cursor -- grb 'git rebase'
    abbr --add --set-cursor -- grh 'git reset --hard'
    abbr --add --set-cursor -- grm 'git rm'
    abbr --add --set-cursor -- grt 'git remote'
    abbr --add --set-cursor -- grv 'git revert'
    abbr --add --set-cursor -- gs 'git status'
    abbr --add --set-cursor -- gsh 'git show'
    abbr --add --set-cursor -- gst 'git stash'
    abbr --add --set-cursor -- gsw 'git switch'
    abbr --add --set-cursor -- gy 'git cherrypick'
    abbr --add --set-cursor -- hy hyprctl
    abbr --add --set-cursor -- hyc 'hyprctl clients'
    abbr --add --set-cursor -- hycj 'hyprctl -j clients'
    abbr --add --set-cursor -- hyd 'hyprctl dispatch'
    abbr --add --set-cursor -- hydj 'hyprctl -j dispatch'
    abbr --add --set-cursor -- hydv 'hyprctl devices'
    abbr --add --set-cursor -- hydvj 'hyprctl -j devices'
    abbr --add --set-cursor -- hyj 'hyprctl -j'
    abbr --add --set-cursor -- hyk 'hyprctl keyword'
    abbr --add --set-cursor -- hykj 'hyprctl -j keyword'
    abbr --add --set-cursor -- hyl 'hyprctl rollinglog'
    abbr --add --set-cursor -- hylj 'hyprctl -j rollinglog'
    abbr --add --set-cursor -- hym 'hyprctl monitors'
    abbr --add --set-cursor -- hymj 'hyprctl -j monitors'
    abbr --add --set-cursor -- hyo 'hyprctl output'
    abbr --add --set-cursor -- hyoj 'hyprctl -j output'
    abbr --add --set-cursor -- hyr 'hyprctl reload'
    abbr --add --set-cursor -- hyrj 'hyprctl -j reload'
    abbr --add --set-cursor -- hys 'hyprctl setprop'
    abbr --add --set-cursor -- hysj 'hyprctl -j setprop'
    abbr --add --set-cursor -- hyv 'hyprctl version'
    abbr --add --set-cursor -- hyvj 'hyprctl -j version'
    abbr --add --set-cursor -- i 'ip -brief'
    abbr --add --set-cursor -- i6 'ip -6 -brief'
    abbr --add --set-cursor -- i6a 'ip -6 -brief address'
    abbr --add --set-cursor -- i6as 'ip -6 -brief address show'
    abbr --add --set-cursor -- i6r 'ip -6 -brief route'
    abbr --add --set-cursor -- i6rs 'ip -6 -brief route show'
    abbr --add --set-cursor -- i6rst 'ip -6 -brief route show table'
    abbr --add --set-cursor -- i6rsta 'ip -6 -brief route show table all'
    abbr --add --set-cursor -- ia 'ip -brief address'
    abbr --add --set-cursor -- ias 'ip -brief address show'
    abbr --add --set-cursor -- ir 'ip -brief route'
    abbr --add --set-cursor -- irs 'ip -brief route show'
    abbr --add --set-cursor -- irst 'ip -brief route show table'
    abbr --add --set-cursor -- irsta 'ip -brief route show table all'
    abbr --add --set-cursor -- jc journalctl
    abbr --add --set-cursor -- jcei 'journalctl --pager-end --identifier'
    abbr --add --set-cursor -- jcfi 'journalctl --follow --identifier'
    abbr --add --set-cursor -- jci 'journalctl --identifier'
    abbr --add --set-cursor -- jcs 'journalctl --system'
    abbr --add --set-cursor -- jcse 'journalctl --system --pager-end'
    abbr --add --set-cursor -- jcsei 'journalctl --user --pager-end --identifier'
    abbr --add --set-cursor -- jcseu 'journalctl --system --pager-end --unit'
    abbr --add --set-cursor -- jcsf 'journalctl --system --follow'
    abbr --add --set-cursor -- jcsfu 'journalctl --system --follow --unit'
    abbr --add --set-cursor -- jcsu 'journalctl --system --unit'
    abbr --add --set-cursor -- jcu 'journalctl --user'
    abbr --add --set-cursor -- jcue 'journalctl --user --pager-end'
    abbr --add --set-cursor -- jcuei 'journalctl --user --pager-end --identifier'
    abbr --add --set-cursor -- jcueu 'journalctl --user --pager-end --unit'
    abbr --add --set-cursor -- jcuf 'journalctl --user --follow'
    abbr --add --set-cursor -- jcufi 'journalctl --user --follow --identifier'
    abbr --add --set-cursor -- jcufu 'journalctl --user --follow --unit'
    abbr --add --set-cursor -- jcui 'journalctl --user --identifier'
    abbr --add --set-cursor -- jcuu 'journalctl --user --unit'
    abbr --add --set-cursor -- k 'kill -9'
    abbr --add --set-cursor -- kj 'kill -9 (jobs --pid)'
    abbr --add --set-cursor -- m mosh
    abbr --add --set-cursor -- n nix
    abbr --add --set-cursor -- nb 'nix build'
    abbr --add --set-cursor -- nd 'nix develop'
    abbr --add --set-cursor -- nf 'nix flake'
    abbr --add --set-cursor -- nfi 'nix flake info'
    abbr --add --set-cursor -- nfl 'nix flake lock'
    abbr --add --set-cursor -- nfu 'nix flake update'
    abbr --add --set-cursor -- ni niri
    abbr --add --set-cursor -- nim 'niri msg'
    abbr --add --set-cursor -- nima 'niri msg action'
    abbr --add --set-cursor -- nimaj 'niri msg --json action'
    abbr --add --set-cursor -- nimfo 'niri msg focused-output'
    abbr --add --set-cursor -- nimfoj 'niri msg --json focused-output'
    abbr --add --set-cursor -- nimfw 'niri msg focused-window'
    abbr --add --set-cursor -- nimfwj 'niri msg --json focused-window'
    abbr --add --set-cursor -- nimj 'niri msg --json'
    abbr --add --set-cursor -- niml 'niri msg layers'
    abbr --add --set-cursor -- nimlj 'niri msg --json layers'
    abbr --add --set-cursor -- nimo 'niri msg output'
    abbr --add --set-cursor -- nimoj 'niri msg --json output'
    abbr --add --set-cursor -- nimos 'niri msg outputs'
    abbr --add --set-cursor -- nimosj 'niri msg --json outputs'
    abbr --add --set-cursor -- nimv 'niri msg version'
    abbr --add --set-cursor -- nimvj 'niri msg --json version'
    abbr --add --set-cursor -- nimw 'niri msg windows'
    abbr --add --set-cursor -- nimwj 'niri msg --json windows'
    abbr --add --set-cursor -- nimwk 'niri msg workspaces'
    abbr --add --set-cursor -- nimwkj 'niri msg --json workspaces'
    abbr --add --set-cursor -- nr 'nix run'
    abbr --add --set-cursor -- nrgl 'nix run github:nix-community/nixGL --impure -- %'
    abbr --add --set-cursor -- nrn 'nix run nixpkgs#%'
    abbr --add --set-cursor -- ns 'nix shell'
    abbr --add --set-cursor -- nsgl 'nix shell github:nix-community/nixGL --impure'
    abbr --add --set-cursor -- nsn 'nix shell nixpkgs#%'
    abbr --add --set-cursor -- nt 'nix store'
    abbr --add --set-cursor -- ol ollama
    abbr --add --set-cursor -- oll 'ollama list'
    abbr --add --set-cursor -- olp 'ollama pull'
    abbr --add --set-cursor -- olr 'ollama run'
    abbr --add --set-cursor -- olrm 'ollama rm'
    abbr --add --set-cursor -- ols 'ollama show'
    abbr --add --set-cursor -- olsrv 'ollama serve'
    abbr --add --set-cursor -- olv 'ollama --version'
    abbr --add --set-cursor -- os nixos
    abbr --add --set-cursor -- osb 'nixos build'
    abbr --add --set-cursor -- osbb 'nixos build boot'
    abbr --add --set-cursor -- osbbo 'nixos build boot -- --offline'
    abbr --add --set-cursor -- osbs 'nixos build switch'
    abbr --add --set-cursor -- osbso 'nixos build switch -- --offline'
    abbr --add --set-cursor -- osbt 'nixos build test'
    abbr --add --set-cursor -- osbto 'nixos build test -- --offline'
    abbr --add --set-cursor -- osd 'nixos diff'
    abbr --add --set-cursor -- osg 'nixos generate'
    abbr --add --set-cursor -- osl 'nixos list'
    abbr --add --set-cursor -- osr 'nixos repl'
    abbr --add --set-cursor -- poweroff 'sudo systemctl poweroff'
    abbr --add --set-cursor -- r reset
    abbr --add --set-cursor -- reboot 'sudo systemctl reboot'
    abbr --add --set-cursor -- restart 'sudo systemctl reboot'
    abbr --add --set-cursor -- rs 'rsync --verbose --info=progress2'
    abbr --add --set-cursor -- s ssh
    abbr --add --set-cursor -- sc systemctl
    abbr --add --set-cursor -- scp 'sudo systemctl poweroff'
    abbr --add --set-cursor -- scr 'sudo systemctl reboot'
    abbr --add --set-cursor -- scs 'sudo systemctl --system'
    abbr --add --set-cursor -- scsd 'sudo systemctl --system disable'
    abbr --add --set-cursor -- scsdn 'sudo systemctl --system disable --now'
    abbr --add --set-cursor -- scse 'sudo systemctl --system reenable'
    abbr --add --set-cursor -- scsen 'sudo systemctl --system reenable --now'
    abbr --add --set-cursor -- scsld 'sudo systemctl --system list-dependencies'
    abbr --add --set-cursor -- scsls 'sudo systemctl --system list-sockets'
    abbr --add --set-cursor -- scslt 'sudo systemctl --system list-timers'
    abbr --add --set-cursor -- scslu 'sudo systemctl --system list-units'
    abbr --add --set-cursor -- scsluf 'sudo systemctl --system list-unit-files'
    abbr --add --set-cursor -- scsm 'sudo systemctl --system mask'
    abbr --add --set-cursor -- scsr 'sudo systemctl --system restart'
    abbr --add --set-cursor -- scsrr 'sudo systemctl --system reload-or-restart'
    abbr --add --set-cursor -- scss 'sudo systemctl --system status'
    abbr --add --set-cursor -- scssh 'sudo systemctl --system show'
    abbr --add --set-cursor -- scst 'sudo systemctl --system stop'
    abbr --add --set-cursor -- scsu 'sudo systemctl --system unmask'
    abbr --add --set-cursor -- scu 'systemctl --user'
    abbr --add --set-cursor -- scud 'systemctl --user disable'
    abbr --add --set-cursor -- scudn 'systemctl --user disable --now'
    abbr --add --set-cursor -- scue 'systemctl --user reenable'
    abbr --add --set-cursor -- scuen 'systemctl --user reenable --now'
    abbr --add --set-cursor -- sculd 'systemctl --user list-dependencies'
    abbr --add --set-cursor -- sculs 'systemctl --user list-sockets'
    abbr --add --set-cursor -- scult 'systemctl --user list-timers'
    abbr --add --set-cursor -- sculu 'systemctl --user list-units'
    abbr --add --set-cursor -- sculuf 'systemctl --user list-unit-files'
    abbr --add --set-cursor -- scum 'systemctl --user mask'
    abbr --add --set-cursor -- scur 'systemctl --user restart'
    abbr --add --set-cursor -- scurr 'systemctl --user reload-or-restart'
    abbr --add --set-cursor -- scus 'systemctl --user status'
    abbr --add --set-cursor -- scush 'systemctl --user show'
    abbr --add --set-cursor -- scut 'systemctl --user stop'
    abbr --add --set-cursor -- scuu 'systemctl --user unmask'
    abbr --add --set-cursor -- shutdown 'sudo systemctl poweroff'
    abbr --add --set-cursor -- si 'ssh -o KexAlgorithms=+diffie-hellman-group1-sha1 -o HostkeyAlgorithms=+ssh-rsa -o Ciphers=aes256-cbc'
    abbr --add --set-cursor -- t 'sudo tailscale'
    abbr --add --set-cursor -- t4 'tailscale ip --4'
    abbr --add --set-cursor -- t6 'tailscale ip --6'
    abbr --add --set-cursor -- td 'sudo tailscale down'
    abbr --add --set-cursor -- te 'sudo tailscale exit-node'
    abbr --add --set-cursor -- ti 'tailscale ip --4 % | wl-copy -n'
    abbr --add --set-cursor -- tii 'tailscale ip --6 % | wl-copy -n'
    abbr --add --set-cursor -- tl 'sudo tailscale login'
    abbr --add --set-cursor -- tlo 'sudo tailscale logout'
    abbr --add --set-cursor -- tn 'tailscale netcheck'
    abbr --add --set-cursor -- tp 'tailscale ping'
    abbr --add --set-cursor -- ts 'tailscale status'
    abbr --add --set-cursor -- tss 'tailscale ssh'
    abbr --add --set-cursor -- tt 'sudo tailscale set'
    abbr --add --set-cursor -- tu 'sudo tailscale up'
    abbr --add --set-cursor -- tuu 'sudo tailscale up --ssh --advertise-exit-node --accept-routes --qr --reset --login-server=https://ts.bjork.tech --auth-key=%'
    abbr --add --set-cursor -- tw 'sudo tailscale switch'
    abbr --add --set-cursor -- txa 'tmux attach'
    abbr --add --set-cursor -- txd 'tmux detach'
    abbr --add --set-cursor -- txk 'tmux kill-session'
    abbr --add --set-cursor -- txl 'tmux list-sessions'
    abbr --add --set-cursor -- w waydroid
    abbr --add --set-cursor -- wa 'waydroid app'
    abbr --add --set-cursor -- waa 'waydroid app launch com.YoStarEN.Arknights'
    abbr --add --set-cursor -- wap 'waydroid app launch com.android.vending'
    abbr --add --set-cursor -- was 'waydroid app launch com.android.settings'
    abbr --add --set-cursor -- wf 'waydroid show-full-ui'
    abbr --add --set-cursor -- wi 'sudo waydroid init --force --system_type GAPPS'
    abbr --add --set-cursor -- ws 'waydroid session'
    abbr --add --set-cursor -- wsh 'sudo waydroid shell'
    abbr --add --set-cursor -- wss 'waydroid session start &> /dev/null & disown'
    abbr --add --set-cursor -- wst 'waydroid session stop'
    abbr --add --set-cursor -- wu 'sudo waydroid upgrade'
    abbr --add --set-cursor -- z 'sudo zerotier-cli'
    abbr --add --set-cursor -- zi 'sudo zerotier-cli get $(sudo zerotier-cli -j listnetworks | jq -r .[-1].id) ip'

    # Disable greeting
    set -g fish_greeting

    if test "$TERM" != dumb
        starship init fish | source
        enable_transience
    end

    set -gx GPG_TTY (tty)
end
